/**
 * Self-hosts the two typefaces and writes everything the browser needs to
 * paint text before they arrive:
 *
 * - `public/fonts/*.woff2`, content-hashed, so the server can cache them for a
 *   year like the rest of the fingerprinted build output
 * - `src/styles/fonts.css`, the @font-face rules plus metric-matched fallbacks:
 *   Arial and Courier New stretched by Capsize to the ascent, descent and
 *   average width of Archivo and Martian Mono, so the swap moves nothing
 * - the preload links in `src/index.html`, for the Latin files only
 *
 *   pnpm fonts
 *
 * Fontsource is the source of the files, pinned in devDependencies; nothing of
 * it ships except the woff2 copied here.
 */
import { createFontStack } from '@capsizecss/core';
import archivo from '@capsizecss/metrics/archivo';
import arial from '@capsizecss/metrics/arial';
import courierNew from '@capsizecss/metrics/courierNew';
import martianMono from '@capsizecss/metrics/martianMono';
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';

const ROOT = new URL('../', import.meta.url);
const PUBLIC_FONTS = new URL('public/fonts/', ROOT);
const FONTS_CSS = new URL('src/styles/fonts.css', ROOT);
const INDEX_HTML = new URL('src/index.html', ROOT);

interface Family {
  readonly name: string;
  readonly fontsource: string;
  readonly weight: string;
  readonly stretch: string;
  readonly metrics: Parameters<typeof createFontStack>[0][number];
  readonly fallback: Parameters<typeof createFontStack>[0][number];
}

const FAMILIES: readonly Family[] = [
  {
    name: 'Archivo',
    fontsource: 'archivo',
    weight: '100 900',
    stretch: '62% 125%',
    metrics: archivo,
    fallback: arial,
  },
  {
    name: 'Martian Mono',
    fontsource: 'martian-mono',
    weight: '100 800',
    stretch: '75% 112.5%',
    metrics: martianMono,
    fallback: courierNew,
  },
];

/** Latin is preloaded; Latin Extended loads on demand, for names such as Pāhala. */
const SUBSETS = ['latin', 'latin-ext'] as const;

function unicodeRange(css: string, file: string): string {
  const block = css.split('@font-face').find((rule) => rule.includes(file));
  const range = block?.match(/unicode-range:\s*([^;]+);/)?.[1];
  if (!range) throw new Error(`No unicode-range for ${file}`);
  return range.trim();
}

async function copyHashed(source: URL, stem: string): Promise<string> {
  const bytes = await readFile(source);
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8).toUpperCase();
  const name = `${stem}-${hash}.woff2`;
  await writeFile(new URL(name, PUBLIC_FONTS), bytes);
  return name;
}

await mkdir(PUBLIC_FONTS, { recursive: true });
for (const stale of await readdir(PUBLIC_FONTS)) {
  if (stale.endsWith('.woff2')) await rm(new URL(stale, PUBLIC_FONTS));
}

const faces: string[] = [];
const fallbacks: string[] = [];
const preloads: string[] = [];

for (const family of FAMILIES) {
  const packageRoot = new URL(`node_modules/@fontsource-variable/${family.fontsource}/`, ROOT);
  const css = await readFile(new URL('standard.css', packageRoot), 'utf8');

  for (const subset of SUBSETS) {
    const file = `${family.fontsource}-${subset}-standard-normal.woff2`;
    const name = await copyHashed(
      new URL(`files/${file}`, packageRoot),
      `${family.fontsource}-${subset}`,
    );
    faces.push(`@font-face {
  font-family: '${family.name}';
  font-style: normal;
  font-display: swap;
  font-weight: ${family.weight};
  font-stretch: ${family.stretch};
  src: url('/fonts/${name}') format('woff2');
  unicode-range: ${unicodeRange(css, file)};
}`);
    if (subset === 'latin') {
      // Laid out the way Prettier formats it, so a regenerated index.html passes format:check.
      preloads.push(
        [
          '    <link',
          '      rel="preload"',
          `      href="/fonts/${name}"`,
          '      as="font"',
          '      type="font/woff2"',
          '      crossorigin',
          '    />',
        ].join('\n'),
      );
    }
  }

  const { fontFaces } = createFontStack([family.metrics, family.fallback], {
    fontFaceFormat: 'styleString',
  });
  // Capsize names the face "<Family> Fallback: <Local>"; the tokens refer to it as "<Family> Fallback".
  fallbacks.push(fontFaces.replace(/"[^"]+ Fallback: [^"]+"/, `"${family.name} Fallback"`));
}

await writeFile(
  FONTS_CSS,
  `/* Generated by scripts/build-fonts.ts (pnpm fonts). Do not edit by hand. */

${faces.join('\n\n')}

/* Local fonts reshaped to the metrics of the ones above, so the swap moves no text. */
${fallbacks.join('\n')}
`,
);

const html = await readFile(INDEX_HTML, 'utf8');
const block = /( *<!-- fonts:start -->\n)[\s\S]*?( *<!-- fonts:end -->)/;
if (!block.test(html)) throw new Error('src/index.html has no <!-- fonts:start/end --> markers');
await writeFile(INDEX_HTML, html.replace(block, `$1${preloads.join('\n')}\n$2`));

console.log(
  `Wrote ${faces.length} faces, ${fallbacks.length} fallbacks, ${preloads.length} preloads`,
);
